spring:
  application:
    name: user
  pid:
    file: app.pid

  datasource:
    url: jdbc:h2:mem:users
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
    tracing:
      sampling:
        probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.troubleshooting.user: DEBUG
    org.zalando.logbook: INFO

logbook:
  format:
    style: json
  include:
    - /**
  obfuscate:
    json-body-fields:
      - password

masking:
  replaceList:
    - regex: "(password=')(.*?)(')"
      replace: "$1***$3"