spring:
  application:
    name: user

  datasource:
    url: jdbc:h2:mem:users
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true